name "blom-couchbase"
version "0.2.0"
author "Ørjan Blom"
project_page "https://github.com/blom/puppet-couchbase"
source "https://github.com/blom/puppet-couchbase"
license "ISC"
summary "Couchbase module"
description "Couchbase module"
dependency "puppetlabs/apt"
dependency "puppetlabs/stdlib"
